version: '3'

services:

  frontend:

    build:

      context: .

    ports:

      - "3000:3000"

    volumes:

      - .:/app

      - ./logs:/app/logs

    env_file:

      - docker.env

    container_name: frontend_smart_evolution

    logging:

      driver: "json-file"

      options:

        max-size: "10m"

        max-file: "3"

    deploy:

      resources:

        limits:

          cpus: "1.0"

          memory: "1G"

    networks:

      - smartevolutionbackend_smartevolution_network

networks:

  smartevolutionbackend_smartevolution_network:

    external: true
