version: '3'

services:
  frontend:
    build:
      context: .
    ports:
      - "3000:3000"
    # COMENTA temporalmente los volúmenes para asegurar que el build 
    # ocurra dentro de la imagen y no se mezcle con archivos locales
    # volumes:
    #   - .:/app
    #   - ./logs:/app/logs
    env_file:
      - docker.env
    container_name: frontend_smart_evolution
    environment:
      - NODE_OPTIONS=--max-old-space-size=2048 # Limita a Node a 2GB de los 3GB disponibles
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "3G"
        reservations:
          memory: "1G" # Reserva mínima para asegurar que arranque
    networks:
      - smartevolutionbackend_smartevolution_network