import Head from "next/head";

import { BrochureListComponent } from "./components";

export default function BrochureList() {
  return (
    <>
      <Head>
        <title>Consulta de Prospectos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BrochureListComponent />
    </>
  );
}
