import Head from "next/head";

import { useFetch } from "@hooks/useFetch";

import { ReceiptListComponent } from "./components";
import { GetBrokerList } from "./queries";

export default function ReceiptList() {
  return (
    <>
      <Head>
        <title>Consulta de recaudos</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ReceiptListComponent />
    </>
  );
}
