import Head from "next/head";

import { BillsComponents } from "./components";

export default function BillList() {
  return (
    <>
      <Head>
        <title>Consulta de facturas</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <BillsComponents />
    </>
  );
}
