import { useEffect, useState } from "react";
import Head from "next/head";
import { useFetch } from "@hooks/useFetch";
import { OperationsComponents } from "./components";
// queries
import { getOperationsVersionTwo,getOperationsVersionTwo2 ,TypeOperation,} from "./queries";

export default function Operations() {
  const [data, setData] = useState([]);
  const [filteredData, setFilteredData] = useState([]);
  const [filters, setFilters] = useState({
    opId: "",
    billId: "",
    investor: "",
  });
  const [typeOp, setTypeOp] = useState([]);

  const [commission, setCommission] = useState(0);
  const [page, setPage] = useState(1);
  const [calcs, setCalcs] = useState({});
  const {
    fetch: getOperationsFetch,
    loading: loadingGetOperations,
    error: errorGetOperations,
    data: dataGetOperations,
  } = useFetch({
    service: () =>getOperationsVersionTwo2 ({ ...filters, page }),
    init: true,
  });


  let dataCount = dataGetOperations?.count || 0;

 // Hooks
    const {
      fetch: fetchTypeIdSelect,
      loading: loadingTypeIdSelect,
      error: errorTypeIdSelect,
      data: dataTypeIdSelect,
    } =  useFetch({ service: TypeOperation, init: true });
        

    

  const filtersHandlers = {
    value: filters,
    set: setFilters,
    get: getOperationsFetch,
    loading: loadingGetOperations,
    error: errorGetOperations,
    data: dataGetOperations?.results || {},
  };
//GET TYPE OPERATION
console.log(filters)
useEffect(() => {
  if (dataTypeIdSelect) {

    var typesID = [];
    dataTypeIdSelect.data.map((typeID) => {
      typesID.push({ label: typeID.description, value: typeID.id });
    });

    setTypeOp(typesID);
  }
}, [dataTypeIdSelect, loadingTypeIdSelect, errorTypeIdSelect]);

useEffect(() => {
    getOperationsFetch();
  }, [filters.opId, filters.billId, filters.investor,filters.startDate, filters.endDate, page]);

  useEffect(() => {
    if (dataGetOperations) {
      dataCount = dataGetOperations?.count || 0;
        const preOperations = dataGetOperations.results
     // const preOperations = dataGetOperations.results.filter(
     //   (x) => x.status >= 3 || x.status == 1
    //  );

      setFilteredData(preOperations);

      if (preOperations?.length == 0) filtersHandlers.data.calcs = {};
    }
  }, [dataGetOperations]);

  useEffect(() => {
    if (dataGetOperations) {
      const checkOperations = dataGetOperations?.results.map(row => {
        const opExpiration = new Date(row.opExpiration + " " + "00:00:00");
        const today = new Date();
        if (opExpiration < today && row.status != 4) {
          return {
            ...row,
            status:5
          }
        }
        return row
      });

      const preOperations = checkOperations
      //const preOperations = checkOperations.filter(
        //(x) => x.status >= 3 || x.status == 1
      //);
      setData(preOperations);
      
      setCalcs(dataGetOperations?.results[0]?.calcs);
    }
  }, [dataGetOperations, loadingGetOperations, errorGetOperations]);


  return (
    <>
      <Head>
        <title>Consulta de pre-operaciones</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <OperationsComponents
        rows2={data}
        typeOperation={dataTypeIdSelect}
        filtersHandlers={filtersHandlers}
        getOperationsFetch={getOperationsFetch}
        calcs={calcs}
        loadingGetOperations={loadingGetOperations}
        page={page}
        setPage={setPage}
        dataCount={dataCount}
        loading={loadingGetOperations}
      />
    </>
  );
}
