import Head from "next/head";

import { useFetch } from "@hooks/useFetch";

import { AccountListComponent } from "./components";
import { GetAccountList } from "./queries";

export default function AccountList() {
  const {
    fetch: fetch,
    loading: loading,
    error: error,
    data: data,
  } = useFetch({ service: GetAccountList, init: true });

  return (
    <>
      <Head>
        <title>Consulta de clientes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <AccountListComponent />
    </>
  );
}
