import Head from "next/head";

import { ClientListComponent } from "./components";

export default function ClientList() {
  return (
    <>
      <Head>
        <title>Consulta de clientes</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <ClientListComponent />
    </>
  );
}
