import { useContext, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/router";
import { Alert, Box, Button, Chip, CircularProgress, Dialog, DialogActions, DialogContent, DialogTitle, FormControl, InputLabel, MenuItem, Paper, Select, Tab, Tabs, TextField, Typography } from "@mui/material";
import { DataGrid } from "@mui/x-data-grid";
import authContext from "@context/authContext";
import { createClientAccess,createUser,getAccessOptions,getAudit,getClientAccess,getPermissions,getRoles,getUsers,saveRole,updateClientAccess,updateUser } from "./queries";

const emptyRole={code:"",name:"",description:"",audience:"INTERNAL",permissions:[]};
const emptyUser={email:"",first_name:"",last_name:"",phone_number:"",roles:[]};

export default function AccessControl({mode="users"}){
  const securityMode=mode==="security";
  const {can,authReady}=useContext(authContext); const router=useRouter();
  const [tab,setTab]=useState(0),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
  const [roles,setRoles]=useState([]),[permissions,setPermissions]=useState([]),[users,setUsers]=useState([]),[access,setAccess]=useState([]),[auditRows,setAuditRows]=useState([]),[options,setOptions]=useState({clients:[],users:[]});
  const [roleForm,setRoleForm]=useState(null),[userForm,setUserForm]=useState(null),[roleUser,setRoleUser]=useState(null),[accessForm,setAccessForm]=useState(null),[blockForm,setBlockForm]=useState(null);
  const load=async()=>{try{setLoading(true);setError("");if(securityMode){const [r,p,logs]=await Promise.all([getRoles(),getPermissions(),getAudit()]);setRoles(r);setPermissions(p);setAuditRows(logs);}else{const [u,a,o]=await Promise.all([getUsers(),getClientAccess(),getAccessOptions()]);setUsers(u);setAccess(a);setOptions(o);setRoles(o.roles||[]);}}catch(e){setError(e.response?.data?.message||"No fue posible cargar la configuración.");}finally{setLoading(false)}};
  useEffect(()=>{const required=securityMode?"security.access":"users.view";if(authReady&&!can(required))router.replace("/dashboard");else if(authReady)load();},[authReady,mode]);
  const modules=useMemo(()=>permissions.reduce((acc,p)=>({...acc,[p.module]:[...(acc[p.module]||[]),p]}),{}),[permissions]);
  const saveNewUser=async()=>{try{const r=await createUser(userForm);setNotice(`Usuario creado. Contraseña temporal: ${r.temporary_password}`);setUserForm(null);load();}catch(e){setError(e.response?.data?.message||"No fue posible crear el usuario.")}};
  const saveAccess=async()=>{try{const r=await createClientAccess(accessForm);setNotice(r.data.temporary_password?`Cuenta creada. Contraseña temporal: ${r.data.temporary_password}`:"Cuenta vinculada correctamente.");setAccessForm(null);load();}catch(e){setError(e.response?.data?.message||"No fue posible vincular la cuenta.")}};
  const userColumns=[
    {field:"email",headerName:"Usuario",flex:1,minWidth:230},{field:"full_name",headerName:"Nombre",flex:1,minWidth:180,valueGetter:p=>`${p.row.first_name||""} ${p.row.last_name||""}`},
    {field:"roles",headerName:"Roles",flex:1,minWidth:220,renderCell:p=><Box>{p.value.map(x=><Chip key={x} size="small" label={x} sx={{mr:.5}}/>)}</Box>},
    {field:"is_active",headerName:"Estado",width:120,renderCell:p=><Chip color={p.value?"success":"error"} label={p.value?"Activo":"Bloqueado"}/>} ,
    {field:"actions",headerName:"Acciones",width:225,renderCell:p=><>{can("users.assign_roles")&&<Button size="small" onClick={()=>setRoleUser({...p.row,roles:[...p.row.roles]})}>Asignar roles</Button>}{can("users.block")&&<Button size="small" color={p.row.is_active?"error":"success"} onClick={()=>updateUser(p.row.id,{is_active:!p.row.is_active}).then(load)}>{p.row.is_active?"Bloquear":"Activar"}</Button>}</>}
  ];
  const roleColumns=[{field:"code",headerName:"Código",width:180},{field:"name",headerName:"Rol",flex:1},{field:"audience",headerName:"Ámbito",width:160},{field:"permissions",headerName:"Permisos",width:130,valueGetter:p=>p.row.permissions.length},{field:"edit",headerName:"",width:100,renderCell:p=>can("roles.update")?<Button onClick={()=>setRoleForm({...p.row,permissions:[...p.row.permissions]})}>Editar</Button>:null}];
  const accessColumns=[{field:"client_name",headerName:"Cliente",flex:1},{field:"user_email",headerName:"Cuenta",flex:1},{field:"status",headerName:"Estado",width:140,renderCell:p=><Chip label={p.value} color={p.value==="ACTIVE"?"success":p.value==="BLOCKED"?"error":"default"}/>},{field:"edit",headerName:"Acciones",width:210,renderCell:p=><>{can("client_access.update")&&<Button size="small" onClick={()=>updateClientAccess(p.row.id,{status:"ACTIVE",blocked_reason:""}).then(load)}>Activar</Button>}{can("client_access.block")&&<Button size="small" color="error" onClick={()=>setBlockForm({...p.row,blocked_reason:""})}>Bloquear</Button>}</>}];
  const auditColumns=[{field:"created_at",headerName:"Fecha",width:190,valueGetter:p=>new Date(p.value).toLocaleString()},{field:"actor_email",headerName:"Ejecutado por",width:240},{field:"action",headerName:"Acción",width:220},{field:"target_type",headerName:"Tipo",width:150},{field:"target_id",headerName:"Registro",flex:1,minWidth:220},{field:"ip_address",headerName:"IP",width:140}];
  if(!authReady||loading)return <Box sx={{p:6,textAlign:"center"}}><CircularProgress/></Box>;
  return <Box><Typography variant="h4" sx={{mb:2}}>{securityMode?"Configuración de seguridad":"Usuarios y cuentas de clientes"}</Typography>{error&&<Alert severity="error" onClose={()=>setError("")} sx={{mb:2}}>{error}</Alert>}{notice&&<Alert severity="success" onClose={()=>setNotice("")} sx={{mb:2}}>{notice}</Alert>}
    <Paper><Tabs value={tab} onChange={(_,v)=>setTab(v)}>{securityMode?[<Tab key="roles" label={`Roles y permisos (${roles.length})`}/>,<Tab key="audit" label={`Auditoría (${auditRows.length})`}/>]:[<Tab key="users" label={`Usuarios (${users.length})`}/>,<Tab key="clients" label={`Cuentas de clientes (${access.length})`}/>]}</Tabs><Box sx={{height:620,p:2}}>
      {!securityMode&&tab===0&&<>{can("users.create")&&<Button variant="contained" sx={{mb:2}} onClick={()=>setUserForm({...emptyUser})}>Crear usuario</Button>}<DataGrid rows={users} columns={userColumns} pageSize={25}/></>}
      {!securityMode&&tab===1&&<>{can("client_access.create")&&<Button variant="contained" sx={{mb:2}} onClick={()=>setAccessForm({client:"",user:"",status:"ACTIVE",create_user:false})}>Vincular o crear cuenta</Button>}<DataGrid rows={access} columns={accessColumns} pageSize={25}/></>}
      {securityMode&&tab===0&&<>{can("roles.create")&&<Button variant="contained" sx={{mb:2}} onClick={()=>setRoleForm({...emptyRole})}>Crear rol</Button>}<DataGrid rows={roles} columns={roleColumns} pageSize={25}/></>}
      {securityMode&&tab===1&&can("audit.view")&&<DataGrid rows={auditRows} columns={auditColumns} pageSize={25}/>} 
    </Box></Paper>

    <Dialog open={!!roleForm} onClose={()=>setRoleForm(null)} fullWidth maxWidth="md"><DialogTitle>{roleForm?.id?"Editar rol":"Crear rol"}</DialogTitle><DialogContent>{roleForm&&<><TextField fullWidth margin="normal" label="Código estable" disabled={!!roleForm.id} value={roleForm.code} onChange={e=>setRoleForm({...roleForm,code:e.target.value.toUpperCase().replace(/\s+/g,"_")})}/><TextField fullWidth margin="normal" label="Nombre" value={roleForm.name} onChange={e=>setRoleForm({...roleForm,name:e.target.value})}/><TextField fullWidth margin="normal" label="Descripción" value={roleForm.description} onChange={e=>setRoleForm({...roleForm,description:e.target.value})}/><FormControl fullWidth margin="normal"><InputLabel>Ámbito</InputLabel><Select label="Ámbito" value={roleForm.audience} onChange={e=>setRoleForm({...roleForm,audience:e.target.value})}><MenuItem value="INTERNAL">Interno</MenuItem><MenuItem value="CLIENT_PORTAL">Portal de clientes</MenuItem></Select></FormControl>{Object.entries(modules).map(([module,items])=><Box key={module} sx={{mt:2}}><Typography fontWeight={700} sx={{textTransform:"capitalize"}}>{module.replaceAll("_"," ")}</Typography>{items.map(p=><Chip key={p.code} clickable color={roleForm.permissions.includes(p.code)?"primary":"default"} label={p.name} onClick={()=>setRoleForm({...roleForm,permissions:roleForm.permissions.includes(p.code)?roleForm.permissions.filter(x=>x!==p.code):[...roleForm.permissions,p.code]})} sx={{m:.5}}/>)}</Box>)}</>}</DialogContent><DialogActions><Button onClick={()=>setRoleForm(null)}>Cancelar</Button><Button variant="contained" disabled={!roleForm?.code||!roleForm?.name} onClick={()=>saveRole(roleForm).then(()=>{setRoleForm(null);load()})}>Guardar</Button></DialogActions></Dialog>

    <Dialog open={!!userForm} onClose={()=>setUserForm(null)} fullWidth><DialogTitle>Crear usuario</DialogTitle><DialogContent>{userForm&&<><TextField fullWidth required margin="normal" label="Correo" value={userForm.email} onChange={e=>setUserForm({...userForm,email:e.target.value})}/><TextField fullWidth margin="normal" label="Nombres" value={userForm.first_name} onChange={e=>setUserForm({...userForm,first_name:e.target.value})}/><TextField fullWidth margin="normal" label="Apellidos" value={userForm.last_name} onChange={e=>setUserForm({...userForm,last_name:e.target.value})}/><FormControl fullWidth margin="normal"><InputLabel>Roles</InputLabel><Select multiple label="Roles" value={userForm.roles} onChange={e=>setUserForm({...userForm,roles:e.target.value})}>{roles.filter(r=>r.state).map(r=><MenuItem key={r.code} value={r.code}>{r.name} ({r.code})</MenuItem>)}</Select></FormControl></>}</DialogContent><DialogActions><Button onClick={()=>setUserForm(null)}>Cancelar</Button><Button variant="contained" disabled={!userForm?.email} onClick={saveNewUser}>Crear</Button></DialogActions></Dialog>

    <Dialog open={!!roleUser} onClose={()=>setRoleUser(null)} fullWidth><DialogTitle>Roles de {roleUser?.email}</DialogTitle><DialogContent>{roleUser&&<FormControl fullWidth margin="normal"><InputLabel>Roles asignados</InputLabel><Select multiple label="Roles asignados" value={roleUser.roles} onChange={e=>setRoleUser({...roleUser,roles:e.target.value})}>{roles.filter(r=>r.state).map(r=><MenuItem key={r.code} value={r.code}>{r.name} ({r.code})</MenuItem>)}</Select></FormControl>}</DialogContent><DialogActions><Button onClick={()=>setRoleUser(null)}>Cancelar</Button><Button variant="contained" onClick={()=>updateUser(roleUser.id,{roles:roleUser.roles}).then(()=>{setRoleUser(null);load()})}>Guardar</Button></DialogActions></Dialog>

    <Dialog open={!!accessForm} onClose={()=>setAccessForm(null)} fullWidth><DialogTitle>Cuenta de acceso para cliente</DialogTitle><DialogContent>{accessForm&&<><FormControl fullWidth margin="normal"><InputLabel>Cliente</InputLabel><Select label="Cliente" value={accessForm.client} onChange={e=>setAccessForm({...accessForm,client:e.target.value})}>{options.clients.map(c=><MenuItem key={c.id} value={c.id}>{c.name} — {c.document_number} {c.roles.length?`[${c.roles.join(", ")}]`:"[Sin clasificación]"}</MenuItem>)}</Select></FormControl><FormControl fullWidth margin="normal"><InputLabel>Cuenta de usuario</InputLabel><Select label="Cuenta de usuario" value={accessForm.user} onChange={e=>setAccessForm({...accessForm,user:e.target.value})}><MenuItem value=""><em>Crear usuario con el correo del cliente</em></MenuItem>{options.users.map(u=><MenuItem key={u.id} value={u.id}>{u.email} — {u.first_name} {u.last_name}</MenuItem>)}</Select></FormControl><Alert severity="info" sx={{mt:2}}>Si no seleccionas usuario, se creará una cuenta con el correo del cliente y se mostrará una contraseña temporal una sola vez.</Alert></>}</DialogContent><DialogActions><Button onClick={()=>setAccessForm(null)}>Cancelar</Button><Button variant="contained" disabled={!accessForm?.client} onClick={saveAccess}>Crear vínculo</Button></DialogActions></Dialog>

    <Dialog open={!!blockForm} onClose={()=>setBlockForm(null)} fullWidth><DialogTitle>Bloquear cuenta de cliente</DialogTitle><DialogContent>{blockForm&&<TextField fullWidth required multiline rows={3} margin="normal" label="Motivo del bloqueo" value={blockForm.blocked_reason} onChange={e=>setBlockForm({...blockForm,blocked_reason:e.target.value})}/>}</DialogContent><DialogActions><Button onClick={()=>setBlockForm(null)}>Cancelar</Button><Button color="error" variant="contained" disabled={!blockForm?.blocked_reason} onClick={()=>updateClientAccess(blockForm.id,{status:"BLOCKED",blocked_reason:blockForm.blocked_reason}).then(()=>{setBlockForm(null);load()})}>Bloquear</Button></DialogActions></Dialog>
  </Box>;
}
