name: Build & Deploy Production

on:
  push:
    branches:
      - main

jobs:
  deploy_to_droplet:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Deploy to Droplet
    steps:
      - name: Connect with SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST_PROD }}
          username: ${{ secrets.SSH_USERNAME_PROD }}
          key: ${{ secrets.SSH_KEY_PROD }}
          port: ${{ secrets.SSH_PORT_PROD }}
          script: |
            cd "${{secrets.PROD_FOLDER}}"
            git pull origin main
            echo "${{ secrets.DOT_ENV_PROD }}" > .env
            npm run build
            sudo docker compose --env-file docker.env up --build -d
            exit
